create table car (
	make VARCHAR(50),
	model VARCHAR(50),
	price DECIMAL(7,2)
);
insert into car (make, model, price) values ('Chrysler', 'LeBaron', 17272.64);
insert into car (make, model, price) values ('Land Rover', 'Discovery', 19464.67);
insert into car (make, model, price) values ('Volkswagen', 'New Beetle', 8215.17);
insert into car (make, model, price) values ('Mercedes-Benz', 'SLK-Class', 3044.4);
insert into car (make, model, price) values ('Land Rover', 'Freelander', 17523.5);
insert into car (make, model, price) values ('Ford', 'Edge', 2677.03);
insert into car (make, model, price) values ('Saab', '9-3', 16489.59);
insert into car (make, model, price) values ('Volvo', 'S40', 18817.15);
insert into car (make, model, price) values ('Nissan', 'Versa', 16141.87);
insert into car (make, model, price) values ('Mazda', 'MPV', 9010.78);
insert into car (make, model, price) values ('Mazda', 'MX-6', 19418.1);
insert into car (make, model, price) values ('GMC', 'Savana 3500', 11240.82);
insert into car (make, model, price) values ('Toyota', 'Tacoma', 3569.24);
insert into car (make, model, price) values ('GMC', 'Vandura 1500', 6009.21);
insert into car (make, model, price) values ('Saab', '9000', 19340.75);
insert into car (make, model, price) values ('Honda', 'Ridgeline', 7845.14);
insert into car (make, model, price) values ('Ford', 'E150', 17630.95);
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', 10834.69);
insert into car (make, model, price) values ('Jaguar', 'XJ Series', 12632.88);
insert into car (make, model, price) values ('Ford', 'E-Series', 2594.65);
insert into car (make, model, price) values ('Ford', 'Escort', 15144.86);
insert into car (make, model, price) values ('Chevrolet', 'Caprice Classic', 19089.63);
insert into car (make, model, price) values ('Hyundai', 'Azera', 13711.81);
insert into car (make, model, price) values ('Mitsubishi', 'Pajero', 14231.57);
insert into car (make, model, price) values ('Cadillac', 'Escalade ESV', 2121.81);
insert into car (make, model, price) values ('Oldsmobile', 'Ciera', 1457.17);
insert into car (make, model, price) values ('Lexus', 'GX', 19856.41);
insert into car (make, model, price) values ('Land Rover', 'Range Rover', 16196.57);
insert into car (make, model, price) values ('Lincoln', 'Navigator L', 14359.11);
insert into car (make, model, price) values ('Ford', 'Mustang', 4519.8);
insert into car (make, model, price) values ('Mazda', 'MX-5', 7377.03);
insert into car (make, model, price) values ('Mitsubishi', 'Eclipse', 13540.12);
insert into car (make, model, price) values ('Lexus', 'GS', 18292.18);
insert into car (make, model, price) values ('BMW', 'M3', 15778.32);
insert into car (make, model, price) values ('Oldsmobile', 'Intrigue', 1186.59);
insert into car (make, model, price) values ('Chevrolet', 'Caprice', 16261.2);
insert into car (make, model, price) values ('Porsche', 'Boxster', 16824.82);
insert into car (make, model, price) values ('Saab', '9-3', 19556.87);
insert into car (make, model, price) values ('Nissan', 'Titan', 8100.3);
insert into car (make, model, price) values ('Honda', 'Odyssey', 9840.27);
insert into car (make, model, price) values ('Buick', 'LeSabre', 10245.46);
insert into car (make, model, price) values ('Hyundai', 'XG350', 1288.9);
insert into car (make, model, price) values ('Toyota', '4Runner', 18037.03);
insert into car (make, model, price) values ('BMW', '7 Series', 15665.52);
insert into car (make, model, price) values ('Ford', 'F350', 1425.34);
