create table person (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	email VARCHAR(150),
	gender VARCHAR(7) NOT NULL,
	date_of_birth DATE NOT NULL,
	country_of_birth VARCHAR(50)
);
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (1, 'Kalinda', 'Raff', null, 'Female', '2022-12-08', 'France');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (2, 'Katinka', 'Lake', null, 'Female', '2023-08-03', 'Kazakhstan');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (3, 'Sarge', 'Roussell', null, 'Male', '2023-06-10', 'Argentina');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (4, 'Lou', 'Pengelley', 'lpengelley3@kickstarter.com', 'Female', '2023-04-25', 'South Korea');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (5, 'Fletch', 'Gossling', null, 'Male', '2022-12-16', 'Indonesia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (6, 'Sibelle', 'Youster', 'syouster5@state.gov', 'Agender', '2023-03-02', 'China');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (7, 'Noak', 'Hawkswell', 'nhawkswell6@pagesperso-orange.fr', 'Male', '2023-08-10', 'China');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (8, 'Christa', 'Candlin', null, 'Female', '2022-11-21', 'Afghanistan');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (9, 'Avery', 'Kirkland', 'akirkland8@ibm.com', 'Male', '2023-03-03', 'Denmark');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (10, 'Trumaine', 'Wayland', null, 'Male', '2023-08-03', 'Brazil');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (11, 'Josephina', 'Crenage', null, 'Female', '2023-01-03', 'Brazil');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (12, 'Avram', 'Hugenin', null, 'Male', '2023-08-09', 'China');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (13, 'Illa', 'Gulleford', null, 'Female', '2022-10-29', 'China');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (14, 'Si', 'Liddall', 'sliddalld@list-manage.com', 'Male', '2023-08-06', 'South Africa');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (15, 'Valencia', 'Roscow', 'vroscowe@gov.uk', 'Female', '2023-05-23', 'Indonesia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (16, 'Codie', 'Valentinuzzi', 'cvalentinuzzif@alexa.com', 'Female', '2023-06-16', 'Indonesia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (17, 'Lelia', 'Edmonston', 'ledmonstong@indiatimes.com', 'Female', '2023-03-27', 'Portugal');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (18, 'Chiquia', 'Fairall', 'cfairallh@istockphoto.com', 'Female', '2023-05-24', 'Brazil');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (19, 'Melisent', 'Godsal', 'mgodsali@bing.com', 'Female', '2023-03-18', 'Portugal');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (20, 'Kaile', 'Faley', 'kfaleyj@gmpg.org', 'Female', '2023-07-29', 'Morocco');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (21, 'Maureen', 'Beloe', 'mbeloek@discuz.net', 'Genderqueer', '2022-12-20', 'Colombia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (22, 'Nikolia', 'Inchcomb', 'ninchcombl@tmall.com', 'Female', '2023-07-15', 'Brazil');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (23, 'Rolfe', 'Piddlehinton', 'rpiddlehintonm@wsj.com', 'Male', '2022-12-19', 'France');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (24, 'Lorilyn', 'Gilffillan', 'lgilffillann@bbc.co.uk', 'Female', '2023-03-25', 'China');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (25, 'Cullan', 'Antoniazzi', 'cantoniazzio@vinaora.com', 'Polygender', '2023-06-16', 'Poland');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (26, 'Leonardo', 'Pennaman', null, 'Male', '2022-11-11', 'Trinidad and Tobago');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (27, 'Pollyanna', 'Roscam', 'proscamq@shutterfly.com', 'Female', '2022-11-20', 'France');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (28, 'Dorothea', 'Simnel', null, 'Female', '2023-04-03', 'Russia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (29, 'Marcos', 'Casassa', 'mcasassas@webeden.co.uk', 'Male', '2023-09-28', 'Palestinian Territory');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (30, 'Javier', 'Janicki', 'jjanickit@nymag.com', 'Male', '2023-02-15', 'Thailand');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (31, 'Wynn', 'Firsby', null, 'Male', '2023-02-09', 'Bulgaria');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (32, 'Janella', 'Rammell', 'jrammellv@rambler.ru', 'Female', '2023-03-11', 'Poland');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (33, 'Worthington', 'Aiskovitch', 'waiskovitchw@naver.com', 'Bigender', '2023-08-03', 'Indonesia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (34, 'Farleigh', 'Leechman', 'fleechmanx@slideshare.net', 'Male', '2023-08-10', 'China');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (35, 'Laurie', 'Evison', 'levisony@spiegel.de', 'Male', '2023-09-22', 'Portugal');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (36, 'Britt', 'Dedden', 'bdeddenz@webeden.co.uk', 'Female', '2022-11-23', 'Sweden');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (37, 'Marlo', 'Eggar', 'meggar10@archive.org', 'Non-binary', '2023-02-22', 'Kyrgyzstan');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (38, 'Bria', 'Noddle', 'bnoddle11@exblog.jp', 'Female', '2023-05-16', 'Japan');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (39, 'Ruttger', 'Strathe', null, 'Male', '2022-12-30', 'Indonesia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (40, 'Katey', 'Coulsen', 'kcoulsen13@tumblr.com', 'Female', '2022-11-28', 'Pakistan');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (41, 'Dorey', 'Hastler', 'dhastler14@chron.com', 'Non-binary', '2022-12-25', 'China');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (42, 'Norene', 'Ivakhno', 'nivakhno15@google.com.hk', 'Female', '2023-05-11', 'Argentina');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (43, 'Cleopatra', 'Capper', null, 'Female', '2023-04-08', 'Syria');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (44, 'Gayel', 'Calderbank', 'gcalderbank17@tripadvisor.com', 'Bigender', '2023-08-22', 'Peru');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (45, 'Libbey', 'Noen', null, 'Female', '2023-03-21', 'Canada');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (46, 'Charlton', 'MacDaid', null, 'Male', '2023-04-01', 'Japan');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (47, 'Bradan', 'Staten', 'bstaten1a@dot.gov', 'Male', '2023-07-20', 'Indonesia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (48, 'Gnni', 'Crolly', 'gcrolly1b@addtoany.com', 'Female', '2023-04-11', 'Mongolia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (49, 'Marya', 'Trevain', 'mtrevain1c@theatlantic.com', 'Female', '2022-12-08', 'Pakistan');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (50, 'Konrad', 'Drover', 'kdrover1d@flavors.me', 'Male', '2023-09-04', 'China');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (51, 'Sabra', 'Morfell', 'smorfell1e@tripod.com', 'Female', '2023-07-03', 'Georgia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (52, 'Wendell', 'Goodge', 'wgoodge1f@example.com', 'Male', '2023-07-06', 'Indonesia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (53, 'Tamiko', 'Hessenthaler', null, 'Female', '2023-08-09', 'Armenia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (54, 'Mara', 'Mawford', null, 'Female', '2023-07-22', 'Morocco');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (55, 'Dore', 'Abrahamoff', 'dabrahamoff1i@gravatar.com', 'Male', '2023-09-10', 'Denmark');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (56, 'Iormina', 'Jedrysik', 'ijedrysik1j@ft.com', 'Female', '2023-08-29', 'Chad');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (57, 'Reine', 'Cuchey', null, 'Agender', '2023-08-21', 'Kenya');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (58, 'Shir', 'Meecher', 'smeecher1l@liveinternet.ru', 'Female', '2023-08-02', 'Pakistan');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (59, 'Cherilyn', 'Chellam', 'cchellam1m@ihg.com', 'Female', '2022-10-10', 'Poland');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (60, 'Emelyne', 'Stickles', null, 'Female', '2023-04-11', 'Indonesia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (61, 'Tessie', 'Vautier', null, 'Female', '2023-04-20', 'Czech Republic');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (62, 'Edgard', 'Dennant', 'edennant1p@craigslist.org', 'Male', '2022-11-14', 'Philippines');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (63, 'Lorettalorna', 'Manketell', 'lmanketell1q@wikipedia.org', 'Female', '2023-03-08', 'Honduras');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (64, 'Borden', 'O''Nowlan', null, 'Male', '2023-05-27', 'France');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (65, 'Marcela', 'Beakes', 'mbeakes1s@europa.eu', 'Female', '2023-08-30', 'Madagascar');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (66, 'Orlando', 'Skyrme', 'oskyrme1t@mlb.com', 'Male', '2023-08-31', 'Brazil');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (67, 'Zea', 'Gilston', 'zgilston1u@tiny.cc', 'Female', '2023-09-17', 'China');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (68, 'Erena', 'Danielsohn', null, 'Female', '2022-10-23', 'Poland');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (69, 'Konstanze', 'Goare', null, 'Female', '2023-02-25', 'Czech Republic');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (70, 'Carrissa', 'Bazley', 'cbazley1x@squidoo.com', 'Female', '2023-01-17', 'Brazil');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (71, 'Godard', 'Spon', null, 'Male', '2023-02-14', 'Canada');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (72, 'Toma', 'Osborne', 'tosborne1z@about.com', 'Genderqueer', '2023-04-02', 'Egypt');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (73, 'Russ', 'Blaxill', 'rblaxill20@europa.eu', 'Male', '2023-08-27', 'Indonesia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (74, 'Jessalyn', 'Swindin', 'jswindin21@mozilla.org', 'Female', '2023-03-20', 'Poland');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (75, 'Quinn', 'Peake', 'qpeake22@prnewswire.com', 'Male', '2023-03-12', 'Mongolia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (76, 'Shae', 'Gurry', 'sgurry23@alibaba.com', 'Genderfluid', '2023-09-11', 'Russia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (77, 'Lionel', 'Gelardi', 'lgelardi24@themeforest.net', 'Male', '2023-02-14', 'Russia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (78, 'Tyler', 'Harragin', 'tharragin25@privacy.gov.au', 'Male', '2023-01-29', 'Indonesia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (79, 'Aylmar', 'Dudman', 'adudman26@hugedomains.com', 'Male', '2022-10-20', 'China');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (80, 'Hyacintha', 'Dick', null, 'Female', '2023-08-30', 'China');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (81, 'Scotti', 'Grishinov', 'sgrishinov28@storify.com', 'Male', '2023-01-11', 'Indonesia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (82, 'Hartley', 'Bottrill', null, 'Male', '2023-07-06', 'Armenia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (83, 'Averill', 'Dodridge', 'adodridge2a@bbb.org', 'Male', '2023-03-14', 'China');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (84, 'Gaylor', 'Passey', 'gpassey2b@cdc.gov', 'Male', '2023-02-21', 'Spain');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (85, 'Haven', 'Vasiliev', 'hvasiliev2c@google.com.hk', 'Male', '2023-05-29', 'China');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (86, 'Melva', 'Stilly', 'mstilly2d@wisc.edu', 'Female', '2023-03-09', 'Portugal');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (87, 'Marrilee', 'Becket', 'mbecket2e@upenn.edu', 'Female', '2023-02-08', 'Nigeria');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (88, 'Dun', 'Selvester', 'dselvester2f@google.com.br', 'Genderfluid', '2023-05-07', 'Nigeria');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (89, 'Peggi', 'Reedshaw', 'preedshaw2g@liveinternet.ru', 'Female', '2023-09-07', 'Poland');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (90, 'Josias', 'Halshaw', 'jhalshaw2h@amazon.de', 'Male', '2023-05-29', 'Thailand');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (91, 'Kathy', 'Crimes', null, 'Female', '2022-11-26', 'Indonesia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (92, 'Lora', 'von Nassau', 'lvonnassau2j@nyu.edu', 'Female', '2023-02-27', 'Argentina');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (93, 'Wendie', 'Klink', 'wklink2k@github.com', 'Female', '2022-11-01', 'China');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (94, 'Kirby', 'Walden', 'kwalden2l@who.int', 'Male', '2023-08-08', 'Vietnam');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (95, 'Dane', 'Asquith', 'dasquith2m@paginegialle.it', 'Male', '2023-08-16', 'Indonesia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (96, 'Land', 'Milan', null, 'Male', '2023-08-06', 'Central African Republic');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (97, 'Anni', 'Francescoccio', 'afrancescoccio2o@miibeian.gov.cn', 'Female', '2023-07-25', 'United States');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (98, 'Oliver', 'Verty', null, 'Male', '2023-01-19', 'Colombia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (99, 'Miriam', 'O''Keenan', 'mokeenan2q@eepurl.com', 'Female', '2023-06-25', 'Czech Republic');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (100, 'Eamon', 'Jeannin', 'ejeannin2r@epa.gov', 'Male', '2023-01-17', 'Indonesia');
