
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Valentina', 'Swateridge', null, 'Female', '2023-08-21', 'Russia', 663.2);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Yettie', 'Ebbrell', 'yebbrell1@house.gov', 'Female', '2023-02-10', 'Indonesia', 657.39);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Sherwynd', 'Spacey', null, 'Male', '2023-07-07', 'China', 581.93);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Rene', 'Trehearne', 'rtrehearne3@google.com.br', 'Male', '2023-08-25', 'Russia', 387.88);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Burl', 'Tripon', 'btripon4@bluehost.com', 'Male', '2023-08-01', 'Indonesia', 130.3);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Sergeant', 'Bittany', 'sbittany5@mozilla.com', 'Non-binary', '2023-09-08', 'Philippines', 473.0);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Lizbeth', 'Pettis', 'lpettis6@yahoo.co.jp', 'Female', '2023-09-12', 'China', 582.13);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Elnora', 'Ferro', 'eferro7@toplist.cz', 'Female', '2023-09-15', 'Thailand', 793.97);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Herrick', 'Rustich', 'hrustich8@smh.com.au', 'Male', '2023-02-04', 'Indonesia', 838.26);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Van', 'Giorgiutti', 'vgiorgiutti9@cisco.com', 'Male', '2022-12-15', 'Aland Islands', 610.83);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Chelsie', 'Castiglio', null, 'Female', '2023-03-10', 'Sweden', 975.47);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Elga', 'De Malchar', 'edemalcharb@google.it', 'Female', '2023-04-20', 'Guatemala', 997.69);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Perle', 'Sempill', null, 'Female', '2022-10-13', 'Ukraine', 94.67);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Rowan', 'Goodread', 'rgoodreadd@unc.edu', 'Male', '2023-05-01', 'China', 846.53);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Esdras', 'Huckster', 'ehuckstere@dagondesign.com', 'Male', '2022-12-08', 'Portugal', 44.83);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Devlen', 'Monnoyer', 'dmonnoyerf@discuz.net', 'Male', '2023-04-05', 'China', 751.96);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Gigi', 'Britton', null, 'Female', '2023-04-17', 'France', 722.55);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Patrice', 'Dunnett', null, 'Female', '2023-07-06', 'United Arab Emirates', 481.64);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Kimberli', 'Brachell', null, 'Female', '2023-01-20', 'Argentina', 651.17);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Franciska', 'Slay', null, 'Female', '2023-06-30', 'United States', 958.77);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Yolane', 'Rosenberg', null, 'Female', '2022-12-17', 'Kazakhstan', 828.7);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Jerrold', 'Hedman', null, 'Male', '2023-08-26', 'Colombia', 855.98);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Dorolisa', 'Joslyn', null, 'Female', '2023-01-20', 'Philippines', 390.95);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Shea', 'Antoszewski', null, 'Female', '2023-09-23', 'China', 174.07);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Aloysius', 'Ronchetti', 'aronchettio@addthis.com', 'Male', '2023-04-26', 'Yemen', 641.74);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Husein', 'Flieger', 'hfliegerp@unicef.org', 'Male', '2023-01-30', 'Philippines', 888.0);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Adel', 'Clawe', 'aclaweq@cnbc.com', 'Female', '2023-07-04', 'Norway', 453.91);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Charmian', 'Brayson', null, 'Female', '2023-09-29', 'China', 429.55);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Fredelia', 'Fratczak', null, 'Female', '2023-08-19', 'Nigeria', 604.12);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Berrie', 'Dulany', null, 'Female', '2022-12-26', 'China', 860.62);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Hamish', 'Connechie', 'hconnechieu@wiley.com', 'Male', '2022-10-06', 'Ukraine', 953.93);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Darrell', 'Skade', 'dskadev@vk.com', 'Male', '2022-10-21', 'Indonesia', 79.14);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Vinnie', 'Orehead', 'voreheadw@list-manage.com', 'Male', '2022-10-29', 'Indonesia', 984.51);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Stevie', 'Billington', 'sbillingtonx@ebay.co.uk', 'Male', '2023-05-05', 'Peru', 897.6);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Pat', 'Tossell', 'ptosselly@bloglovin.com', 'Male', '2023-02-05', 'Portugal', 667.7);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Agnese', 'Gregorio', 'agregorioz@illinois.edu', 'Non-binary', '2023-10-05', 'Angola', 201.91);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Mirabella', 'Gerber', 'mgerber10@uiuc.edu', 'Female', '2023-05-21', 'Iran', 266.42);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Sigismundo', 'Nuttey', 'snuttey11@skyrock.com', 'Male', '2022-12-12', 'Iran', 490.1);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Brianne', 'Fehners', 'bfehners12@bigcartel.com', 'Female', '2023-09-22', 'Russia', 129.63);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Duff', 'Dobsons', 'ddobsons13@youku.com', 'Male', '2023-02-09', 'Brazil', 101.85);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Shirleen', 'Menendez', 'smenendez14@list-manage.com', 'Female', '2023-08-14', 'China', 924.16);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Raf', 'Petruk', 'rpetruk15@angelfire.com', 'Female', '2023-03-30', 'Portugal', 170.71);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Renaldo', 'Winear', 'rwinear16@merriam-webster.com', 'Male', '2023-01-13', 'Peru', 917.67);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Walker', 'Fullwood', 'wfullwood17@networksolutions.com', 'Male', '2023-01-26', 'China', 887.63);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Caz', 'Bosket', 'cbosket18@drupal.org', 'Male', '2022-12-23', 'Pakistan', 473.89);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Donetta', 'Fassbindler', 'dfassbindler19@china.com.cn', 'Female', '2022-12-29', 'China', 422.01);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Maggie', 'Hawick', null, 'Agender', '2023-04-24', 'Russia', 999.47);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth, price) values ('Mae', 'Courtese', 'mcourtese1b@patch.com', 'Genderqueer', '2023-09-15', 'Argentina', 708.67);
